### PR TITLE
change to qt5 from qt4

### PR DESCRIPTION
**Pull request by iamybj**
### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Please delete the parts of the pull request template that are not relevant and fill out the rest.

**Comment by iamybj** [comment]
why still not merged ?

**Comment by reitermarkus** [comment]
> and fill out the rest.

You deleted the checklist from the [pull request template](https://github.com/caskroom/homebrew-cask/blob/master/.github/PULL_REQUEST_TEMPLATE.md). Please add this checklist to the top post.

> why still not merged ?

You submitted this PR a mere 25 minutes ago, not all maintainers are up at a given time, so you cannot expect a response time this fast.

**Comment by iamybj** [comment]
I find that brew and brew cast both cannot install apps from others git repositories for testing.

**Comment by reitermarkus** [comment]
> I find that brew and brew cast both cannot install apps from others git repositories for testing.

What exactly do you mean?

**Comment by iamybj** [comment]
I mean,  people should install the modified pkg.rb from their own git repo, correct the errors if any, and then pull request to brew/cast git repo.

**Comment by reitermarkus** [comment]
Usually people modify and test the Cask files locally, as they most likely already have `brew cask` installed.

You can however pass a full URL to `brew cask install`, like this:

```bash
brew cask install https://raw.githubusercontent.com/iamybj/homebrew-cask/0d2cc2cc9cf26ccc6644efb2ea7b5289d64d51d4/Casks/liteide.rb
```

**Pull request merged**
